### ISSUE TITLE
Use CSS grid layout instead of wacky positioning

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/expense-manager-demo#60]
Right now, some of the breakpoints are using some pretty hacky stuff, replace with css grid.

**Comment by tomivirkki** [comment]
In order to keep supporting Safari 9 we can't switch to CSS grid just yet. We can however better utilize Vaadin layouts such as `<vaadin-form-layout>`, `vaadin-ordered-layout` and `<vaadin-split-layout>`.

See "Layout" at https://docs.google.com/document/d/11A8ScBF03__GskbOOylnWD1z_4BlZJm8tpMXCIX7Qb0/edit#
