### ISSUE TITLE
Clean up bower.json

### ISSUE THREAD

**Issue by marcushellberg** [vaadin/expense-manager-demo#84]
Depend on `vaadin-core` instead of individual elements. Remove unused components.

**Comment by web-padawan** [comment]
Do we really want to install all the `vaadin-core`? Currently only the used elements are listed. I recently did some cleanup in 365df68

BTW, I'm wondering if we should promote installing `vaadin-core` as a bower collection at all, because it is likely to be intended for using as part of the platform now.

**Comment by marcushellberg** [comment]
The benefit would be that it is easy to update it and users can always be sure to get compatible versions of components. The build step will ensure that only the needed ones are bundled. 

@Artur- we talked about `vaadin-core` earlier today. What are your thoughts? I think that this would be a prime use case for it.

**Comment by web-padawan** [comment]
I would say that the version range should work as well, unless we get `beta10` released (which we hope to avoid) or introduce breaking changes by accident.

BTW, we decided not to use `vaadin-horizontal-layout` in the Expense Manager just because of the fact that this element was considered as intended to be used by Flow, and therefore not to be promoted as a standalone. This can of course be reconsidered at some point.
